version: "3.7"

services : 

  frontend:
    image: gitlab-registry.imt-atlantique.fr/z22amhid/fil_rouge_gitlab_ci/front_prod
    environment:
      VAPORMAP_BACKEND: 10.29.245.12
      VAPORMAP_BACKEND_PORT: 8001      
      VAPORMAP_URL_SERVERNAME: 0.0.0.0
      VAPORMAP_URL_PORT: 80
      VAPORMAP_FRONTEND_ROOT: /frontend
    ports:
      - "8000:80"
    deploy:
      replicas: 3
      
  backend:
    image: gitlab-registry.imt-atlantique.fr/z22amhid/fil_rouge_gitlab_ci/back_prod
    ports:
      - "8001:5000"
    deploy:
      replicas: 3

    
    environment:
      VAPOR_DBNAME: db_vapormap
      VAPOR_DBUSER: user_vapormap
      VAPOR_DBPASS: vapormap
      VAPOR_DBHOST: vap_db
      FLASK_APP: app
      PYTHONPATH: /app
      SETTINGS_FILE: production
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1

    depends_on:
      - vap_db

  vap_db:
    image: gitlab-registry.imt-atlantique.fr/z22amhid/fil_rouge_gitlab_ci/vap_db
    environment:
     
      MARIADB_DATABASE: db_vapormap
      MARIADB_USER: user_vapormap
      MARIADB_PASSWORD: vapormap
      MARIADB_RANDOM_ROOT_PASSWORD: 1

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

    
    volumes:
      - vap_db:/var/lib/mysql/

volumes:
  vap_db:

